name: inventario_qr
description: Sistema de inventario multi-artículo bajo modelo QR con restricciones
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Gestión de estado
  provider: ^6.1.5
  # Manejo de Excel
  excel: ^4.0.6
  file_picker: ^10.2.0
  path_provider: ^2.1.2
  # Abrir archivos
  open_file: ^3.5.10
  # Google Fonts
  google_fonts: ^6.3.0
  # Gráficas para visualización de datos
  syncfusion_flutter_charts: ^30.1.42
  # Iconos Unicons
  unicons: ^3.0.0
  # Tabla avanzada con edición Excel
  pluto_grid: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
